### ISSUE TITLE
予約一覧の表示方法改善：予約が多い場合のUI改善

### ISSUE THREAD

**Issue by ak-kitsuda** [ak-kitsuda/kaigi-test#1]
## 問題の概要
現在の会議室予約システムでは、予約数が多くなると予約一覧が縦に長く表示されるため、画面全体が非常に長くなってしまう問題があります。ユーザーが多くの予約を管理する場合、スクロールが多くなり使いづらくなっています。

## 現在の実装
現在の実装では、`displayReservations`関数内で予約データを縦にリストとして表示しています。

```javascript:main.js
function displayReservations(roomFilter) {
  const reservationList = document.getElementById('reservationList');
  reservationList.innerHTML = '';

  // 日付でソート
  const sortedReservations = [...reservations].sort((a, b) =>
    new Date(a.startDate) - new Date(b.startDate)
  );

  // 部屋でフィルタリング
  let filteredReservations = roomFilter === 'all'
    ? sortedReservations
    : sortedReservations.filter(r => r.room === roomFilter);

  // 予約アイテムを縦に並べて表示
  filteredReservations.forEach(reservation => {
    const reservationItem = document.createElement('div');
    reservationItem.className = 'reservation-item';
    // 予約アイテムの内容を構築
    // ...
    reservationList.appendChild(reservationItem);
  });
}
```

CSSにおいても、各予約アイテムは縦に積み重なるよう設定されています：

```css:styles.css
.reservation-item {
  border: 1px solid #e0e0e0;
  padding: 20px;
  margin-bottom: 15px;
  border-radius: 10px;
  background-color: #fafafa;
  transition: all 0.2s;
}
```

## 期待される動作
予約一覧の表示方法を改善し、予約が多い場合でも画面の長さが過度に長くならないUIを実現する。

## 改善案
以下のいずれかの方法で実装することを検討してください：

1. **ページネーション機能の追加**
   - 一度に表示する予約数を制限（例：10件ずつ）し、ページ切り替え機能を追加

2. **カード型グリッドレイアウトへの変更**
   - 予約アイテムをカード形式でグリッドレイアウトに配置
   - レスポンシブに画面幅に応じて列数を調整

3. **アコーディオン形式による日付ごとのグループ化**
   - 予約を日付ごとにグループ化し、日付見出しをクリックで開閉できるアコーディオン形式に変更

4. **仮想スクロールの導入**
   - 画面に表示されている部分のみをレンダリングする仮想スクロール技術の導入

## 備考
- モバイル端末での使いやすさも考慮したデザインにすること
- 既存のフィルタリング機能（部屋タイプ、日付）は維持すること
